USE OWL;
INSERT INTO Matches (team1, team2, victory, defeat) VALUES
(SFS, TOR, SFS, TOR),
(WAS, LDN, WAS, LDN),
(VAN, FLA, FLA, VAN),
(NYE, ATL, ATL, NYE),
(HOU, GLA, HOU, GLA),
(VAN, VAL, VAN, VAL),
(DAL, GZC, GZC, DAL),
(HZS, SHD, HZS, SHD),
(WAS, LVE, WAS, LVE),
(VAL, HOU, HOU, VAL),
(NYE, BOS, BOS, NYE),
(SFS, ATL, ATL, SFS),
(LVE, FLA, FLA, LVE),
(LDN, BOS, BOS, LDN),
(TOR, GLA, GLA, TOR);
