USE OWL;

INSERT INTO GameMaps (id, name, mode) VALUES
('ANP', 'Antarctic Peninsula', 'Control'),
('BUS', 'Busan', 'Control'),
('ILI', 'Ilios', 'Control'),
('LIJ', 'Lijiang Tower', 'Control'),
('NEP', 'Nepal', 'Control'),
('OAS', 'Oasis', 'Control'),
('SAM', 'Samoa', 'Control'),
('CIR', 'Circuit Royal', 'Escort'),
('DOR', 'Dorado', 'Escort'),
('HAV', 'Havana', 'Escort'),
('JUN', 'Junkertown', 'Escort'),
('RIA', 'Rialto', 'Escort'),
('R66', 'Route 66', 'Escort'),
('SHA', 'Shambali Monastery', 'Escort'),
('WPG', 'Watchpoint: Gibraltar', 'Escort'),
('NJC', 'New Junk City', 'Flashpoint'),
('SUR', 'Suravasa', 'Flashpoint'),
('BLI', 'Blizzard World', 'Hybrid'),
('EIC', 'Eichenwalde', 'Hybrid'),
('HOL', 'Hollywood', 'Hybrid'),
('KNG', 'King\'s Row', 'Hybrid'),
('MID', 'Midtown', 'Hybrid'),
('NUM', 'Numbani', 'Hybrid'),
('PAR', 'Paraíso', 'Hybrid'),
('COL', 'Colosseo', 'Push'),
('ESP', 'Esperança', 'Push'),
('NQS', 'New Queen Street', 'Push');
