USE OWL;

INSERT INTO Teams (id, name) VALUES ('ATL', 'Atlanta Reign');
INSERT INTO Teams (id, name) VALUES ('BOS', 'Boston Uprising');
INSERT INTO Teams (id, name) VALUES ('CDH', 'Chengdu Hunters');
INSERT INTO Teams (id, name) VALUES ('DAL', 'Dallas Fuel');
INSERT INTO Teams (id, name) VALUES ('FLA', 'Florida Mayhem');
INSERT INTO Teams (id, name) VALUES ('GZC', 'Guangzhou Charge');
INSERT INTO Teams (id, name) VALUES ('HZS', 'Hangzhou Spark');
INSERT INTO Teams (id, name) VALUES ('HOU', 'Houston Outlaws');
INSERT INTO Teams (id, name) VALUES ('LDN', 'London Spitfire');
INSERT INTO Teams (id, name) VALUES ('GLA', 'Los Angeles Gladiators');
INSERT INTO Teams (id, name) VALUES ('VAL', 'Los Angeles Valiant');
INSERT INTO Teams (id, name) VALUES ('NYE', 'New York Excelsior');
INSERT INTO Teams (id, name) VALUES ('SFS', 'San Francisco Shock');
INSERT INTO Teams (id, name) VALUES ('SEO', 'Seoul Dynasty');
INSERT INTO Teams (id, name) VALUES ('SIN', 'Seoul Infernal');
INSERT INTO Teams (id, name) VALUES ('SHD', 'Shanghai Dragons');
INSERT INTO Teams (id, name) VALUES ('TOR', 'Toronto Defiant');
INSERT INTO Teams (id, name) VALUES ('VAN', 'Vancouver Titans');
INSERT INTO Teams (id, name) VALUES ('VEG', 'Vegas Eternal');
INSERT INTO Teams (id, name) VALUES ('WAS', 'Washington Justice');